#!/bin/bash

smartPath=`pwd`
#加载公共smart函数库
. ./shell/smartfunc/smartfunc

#加载base函数库
. ./shell/smartfunc/basefunc

#加载项目函数库
. ./shell/smartfunc/govfunc
. ./shell/smartfunc/protalfunc
. ./shell/smartfunc/apifunc
. ./shell/smartfunc/reversefunc
. ./shell/smartfunc/sharefunc
. ./shell/smartfunc/appfunc

case $1 in
'install')
  installBasement
  installApi
  installGov
  installPortal
  installShare
  installApp
  startReverse
  ;;
'start')
  startBasement
  startApi
  startGov
  startPortal
  startShare
  startApp
  startReverse
  ;;
'stop')
  stopBasement
  stopApi
  stopGov
  stopPortal
  stopApp
  stopShare
  stopReverse
  ;;
'clear')
  clearBasement
  clearApi
  clearGov
  clearShare
  clearApp
  clearPortal
  ;;
'upgrade')
  clearApi
  clearGov
  clearPortal
  clearApp
  clearShare
  clearReverse
  startApi
  startGov
  startPortal
  startApp
  startShare
  startReverse
  ;;
'update-portal')
  updatePortal
  ;;
'update-api')
  updateApi
  ;;
'update-gov')
  updateGov
  ;;
'update-share')
  updateShare
  ;;
*)
  menu
esac
