#!/bin/bash

function startReverse {
  cd reverse && docker-compose up -d
  if [ $? -ne 0 ]
  then
    echo 'recreate revers'
    docker-compose rm -f && docker-compose up -d
  fi
}

function stopReverse {
  cd reverse && docker-compose stop && cd $smartPath
}

function clearReverse {
  cd reverse && docker-compose rm -f && docker-compose pull && cd $smartPath
}
