#!/bin/bash

function installShare {
  if [ ! -d "./px-frontend-share" ]; then
    cd $smartPath && git clone https://code.aliyun.com/pingxiang/px-frontend-share.git
  fi
  cd px-frontend-share && git checkout dev && docker-compose up -d && cp pre-commit .git/hooks && cp pre-push .git/hooks && ./smart composer && cd $smartPath
}

function startShare {
  cd px-frontend-share && git checkout dev && docker-compose up -d && cd $smartPath
}

function stopShare {
  cd px-frontend-share && git checkout dev && docker-compose stop && cd $smartPath
}

function clearShare {
  cd px-frontend-share && git checkout dev && docker-compose stop && docker-compose rm -f && docker-compose pull && cd $smartPath
}

function updateShare {
  cd px-frontend-share && git checkout dev && git pull origin dev && cd $smartPath
}
