#!/bin/bash

function menu {
	echo 
	echo -e "\t\t\t萍乡项目控制脚本\n"
	echo -e "\t\t使用方法: smart command. 如: ./smart start 启动服务\n"
	echo -e "\t\t\tREAD \t\t\tME\n"
	echo -e "\t\t绑定hosts文件 portal.pingxiang.com 127.0.0.1 门户网\n"
	echo -e "\t\t绑定hosts文件 gov.pingxiang.com 127.0.0.1 政务网\n"
	echo -e "\t1. install: 安装服务\n"
	echo -e "\t2. start: 启动服务\n"
	echo -e "\t3. stop: 关闭服务\n"
  echo -e "\t4. clear 清除环境,可以清除容器后重新启动\n"
  echo -e "\t5. upgrade 更新环境\n"
	echo -e "\t6. update-portal 更新门户网代码\n"
	echo -e "\t7. update-gov 更新政务网代码\n"
	echo -e "\t8. update-api 更新后端接口代码\n"
}
